use_frameworks!

platform :ios, '8.0'

target 'AppCommonTool_Example' do
  pod 'AppCommonTool', :path => '../'

  target 'AppCommonTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
